### PR TITLE
Add helper scripts + Slight rewrite of the README.

### PR DESCRIPTION
**Pull request by thusc**
Yo @asheshambasta, let me know if you'd like me to change some things.

Can you tell me what I should run to benefit from Brittany and HLint ? I'll add the information to the README too.

### CODE REVIEW

**Review by asheshambasta — APPROVED** [review]

**Comment by asheshambasta** [comment]
@thusc As for the comment about brittany and hlint; these depend on the editor you're using. 
For emacs; you need to allow local variables in `.dir-locals.el` which will enable brittany for formatting the source code. 

For enabling HLint, however, this depends on your haskell integration for your editor. In my case, I use `dante` which can have HLint support: 
``` elisp 
        (add-hook 'dante-mode-hook
                  '(lambda () ( flycheck-add-next-checker 'haskell-dante
                               '(warning . haskell-hlint)
        )))
```
This enables dante to display HLint suggestions/warnings in your editor. 

However, these are editor specific instructions. I don't know how to do the same in Vim, although its possible.

**Comment by thusc** [comment]
Oh ok. My question was more about how can I run hlint or brittany from the command-line, and make sure that if I apply what they suggest, I'm indeed following waht the project "guidelies" are.

**Comment by asheshambasta** [comment]
@thusc 

1. We can run brittany over the whole project with a combination of `find . -name '*.hs' -print -exec brittany --write-mode inplace {} \;` 
2. For HLint, we can possibly follow something similar: `find . -name '*.hs' -print -exec hlint {} \;` 

However, I think for HLint you'd like to run it on the modified files. We can possibly add git commit hooks that ensures `HLint` runs on modified files only, and git only agrees to commit if there are no _hints_ (HLint calls all warnings/improvement suggestions _hints_). 

However, this also involves git and adds complexity to the workflow (which is already complex owing to Nix etc.)

**Comment by thusc** [comment]
If you agree with the PR, @asheshambasta can you merge it ?

**Pull request merged**
